### ISSUE TITLE
docs: structrtcTime.html and structRTCtime.html causes browser to pick whichever one comes first

### ISSUE THREAD

**Issue by lifehackerhansol** [blocksds/sdk#137]
Due to the identical naming of these without the capitals, doxygen is creating two case-sensitive files.

Browser (or GitHub Pages?) is returning whichever one got cached first.

This behaviour seems to differ based on specific conditions (for example, in a Incognito window, it has no issues differentiating between the two, but on Edge default, it is caching a single version.)

**Comment by AntonioND** [comment]
That's weird, maybe it only happens in Windows?

I assume you are talking about the following two pages, and they work for me:

- https://blocksds.github.io/docs/libnds/structRTCtime.html
- https://blocksds.github.io/docs/libnds/structrtcTime.html

In any case, this is tricky. I can't change the names of the structs just because Doxygen isn't doing a good job with their names. Maybe there is some way to get Doxygen to generate page names in a different way...

**Comment by lifehackerhansol** [comment]
You're right, it doesn't seem to be a doxygen issue; definitely something weird going on with select browsers.

I'll try to see if I can reproduce it; currently Firefox seems to be okay.

**Comment by AntonioND** [comment]
https://www.w3.org/TR/WD-html40-970708/htmlweb.html

> URLs in general are case-sensitive (with the exception of machine names). There may be URLs, or parts of URLs, where case doesn't matter, but identifying these may not be easy. Users should always consider that URLs are case-sensitive.

This looks like a web browser bug, not a Doxygen bug...

**Comment by AntonioND** [comment]
@lifehackerhansol did you check this in the end?

**Comment by AntonioND** [comment]
I'm closing this issue as it looks like it's a browser issue. I can reopen it if needed.
