### ISSUE TITLE
tinystdio setvbuf() flushes on every seek

### ISSUE THREAD

**Issue by asiekierka** [blocksds/sdk#23]
In picolibc's tinystdio implementation, it appears that `setvbuf()` combined with seeking operations on the open file always forces a flush, which means that the virtual buffer may be reloaded much more often than expected, causing significant slowdowns.

**Comment by AntonioND** [comment]
Some extra context.

``setvbuf()`` sets the ``size`` variable in the stream struct:

https://github.com/picolibc/picolibc/blob/35c504ff6065b2a87ea8a106ae0d0d61d1e7ece5/newlib/libc/tinystdio/bufio.c#L251

And ``fread()`` calls ``fgetc()`` as many times as bytes it has to read, and ``fgetc()`` calls ``__bufio_get()``. When the user tries to read anything from outside of the current buffer loaded in picolibc, ``__bufio_get()`` calls ``read()`` to read as much space as specified in ``setvbuf()``.

https://github.com/picolibc/picolibc/blob/35c504ff6065b2a87ea8a106ae0d0d61d1e7ece5/newlib/libc/tinystdio/bufio.c#L158

In the case of MegaZeux this is particularly bad because the buffer size is is 32 KB:

https://github.com/AliceLR/megazeux/blob/8e39315a70b5ca871bfb55b1ab632b272e3d1854/src/io/vio.c#L42

**Comment by AntonioND** [comment]
It looks like it's just a problem of ``tinystdio``.

This is the ``fread()`` of ``tinystdio`` in picolibc:

https://github.com/picolibc/picolibc/blob/35c504ff6065b2a87ea8a106ae0d0d61d1e7ece5/newlib/libc/tinystdio/fread.c

This one is the one in ``stdio``, the default in newlib:

https://github.com/picolibc/picolibc/blob/35c504ff6065b2a87ea8a106ae0d0d61d1e7ece5/newlib/libc/stdio/fread.c

It looks like it's just better optimized. Maybe the solution is to switch to regular stdio in the picolibc build, or to not use big buffers with picolibc.

**Comment by AntonioND** [comment]
So yeah, it looks like this is the expected behaviour. The two options are:

1. Switch to regular stdio from newlib. The code footprint is bigger, but the performance is better with big ``setvbuf()``.
2. Stick to tinystdio and accept that using ``setvbuf()`` just has this effect.

I don't know how bad will be 1 regarding code footprint, though.

https://www.gnu.org/software/libc/manual/html_node/Controlling-Buffering.html

> The value of BUFSIZ is chosen on each system so as to make stream I/O efficient. So it is a good idea to use BUFSIZ as the size for the buffer when you call setvbuf.

**Comment by asiekierka** [comment]
This assessment isn't quite right. Were the problem in `fread()`, performance would've been bad both with `setvbuf()` disabled and enabled - but it's not, the performance is *much* better with `setvbuf()` disabled. In my experience, the performance is sufficient (that is, not a noticeable slowdown factor) in my workloads with tinystdio enabled, compared to legacy stdio.

The actual problem is here:

https://github.com/picolibc/picolibc/blob/35c504ff6065b2a87ea8a106ae0d0d61d1e7ece5/newlib/libc/tinystdio/bufio.c#L187-L188

Calling `fseek()` changes the "direction" of the stream to `0` (from available options `0`, `read`, `write`), which forces a stream flush - and thus, dropping the contents of the buffer.

**Comment by asiekierka** [comment]
This will be solved in 0.11.0. The picolibc patch is ready.
