### ISSUE TITLE
Diagnose DSi SD card stability

### ISSUE THREAD

**Issue by asiekierka** [blocksds/sdk#24]
It seems, in testing, that very heavy reads (many hundreds of sector read requests) to the DSi SD card can, in some cases, cause an ARM9 freeze. ARM7 appears unimpacted. This should be investigated further. Reproducible on MegaZeux's DS port.

**Comment by profi200** [comment]
I was asked to comment on this. Is this reproducible with different SD cards? I'm currently not aware of problems with the old sdmmc driver or libfat other than the later not updating the second FAT.

**Comment by asiekierka** [comment]
Ah, apologies. It appears specific to BlocksDS; I haven't managed to reproduce it on libnds+libfat.

**Comment by profi200** [comment]
I looked around a bit and saw this is using FatFs instead of libfat. Had a good experience with FatFs too so far.

A little detail i forgot to mention earlier but the old sdmmc driver has one issue. If the SD card ever throws an error during transfer the driver can't recover and needs a reinit. The SD would only do that if it's already close to dead (ECC errors) or it has write protected blocks.

Since i'm not familiar with this project all i can do is ask you to do some debugging. See where exactly it hangs. Since you said it's the ARM9 that hangs is suspect IPC bugs or something else.

**Comment by asiekierka** [comment]
As I said, it's mostly an issue of time and getting a consistent reproduction; essentially, someone needs to sit down and write a "stress test" .nds file, then it has to be tweaked until it can consistently reproduce the freeze I'm getting. I'd also need to check, as you hinted at, if it's not specific to a given microSD card - I do have a fair few.

**Comment by AntonioND** [comment]
I've created this stress test for this issue, but it just works for me:

https://github.com/blocksds/sdk/tree/1b87f73d57bc5296ac2bf9eedb40e96614bef1b4/tests/filesystem/stress_test

**Comment by asiekierka** [comment]
Can no longer reproduce with https://github.com/blocksds/libnds/commit/34528657d628baf63d8c0a2eed0890bec23d0a0c

**Comment by profi200** [comment]
Sounds like i called it when i mentioned IPC bugs. :)

**Comment by asiekierka** [comment]
Can reproduce again after the last batch of FIFO changes.

**Comment by asiekierka** [comment]
I think this can be closed in favor of https://github.com/blocksds/sdk/issues/49 at this point - integrating a better DSi SD card driver can be tackled separately.
