### ISSUE TITLE
Investigate if it's possible to make a GPU-safe ARM7 exit-to-loader handler

### ISSUE THREAD

**Issue by AntonioND** [blocksds/sdk#45]
When the ARM7 requests a reset, the ARM9 gets a FIFO message, which interrupts the execution. At that point, the reset process starts between the two CPUs.

If this interrupt happens in between sending the vertices of a polygon to the GPU, if the loader (or any other application it loads) tries to use the 3D GPU it will lock up:

https://www.problemkaputt.de/gbatek.htm

> SwapBuffers should not be issued within Begin/End. The two parameter bits of the SwapBuffers command are used for the following gxcommands (ie. not for the old gxcommands prior to SwapBuffers).
>
> SwapBuffers does lock-up the 3D hardware if an incomplete polygon list has been defined (eg. a triangle with only 2 vertices). On lock-up, only 2D video is kept working, any wait-loops for GXSTAT.27 will hang the program. Once lock-up has occured, there seems to be no way to recover by software, not by sending the missing veric(es), and not even by pulsing POWCNT1.Bit2-3.

There may be some way to prevent this lockup from happening.

**Comment by asiekierka** [comment]
https://github.com/blocksds/libnds/pull/19

This mitigates the lockup from happening if SwapBuffers has not been called yet, but a partial vertex is uploaded to the 3D geometry engine (as would happen f.e. due to a forced reset in the middle of processing a vertex list).

I would advise against doing this on exit - the exit, especially a hang-related reset (as an ARM7-triggered one would probably be), should be as simple as possible, as "who knows what caused the hang"?

**Comment by AntonioND** [comment]
> I would advise against doing this on exit - the exit, especially a hang-related reset (as an ARM7-triggered one would probably be), should be as simple as possible, as "who knows what caused the hang"?

Fair enough.

I've merged the PR, so I guess this task can be closed now.
