### ISSUE TITLE
Check ``readFirmware()`` function

### ISSUE THREAD

**Issue by AntonioND** [blocksds/sdk#51]
``readFirmware()`` seems to be unreliable. Maybe we can try to fix it by changing the speed here:

https://github.com/blocksds/libnds/blob/fdd196d81d20ce6a5f50ad7d560b670fd7b7c865/source/arm7/firmware.c#L44

```
#define SPI_BAUD_4MHz    0
#define SPI_BAUD_2MHz    1
#define SPI_BAUD_1MHz    2
#define SPI_BAUD_512KHz  3
```

**Comment by lifehackerhansol** [comment]
The readFirmware() function seems to actually be fine.

It seems our previous discussion on firmware headers were rather misguided. Mostly from me, because I found that I had a poor understanding of what an actually functional firmware dump is supposed to look like.

As observed in https://github.com/DS-Homebrew/dsbf_dump/commit/ffb01b08d976bcc5c263d54396b2518e94f64ab2, DC_InvalidateRange appears to be mandatory for firmware reads, possibly only really the case for large reads such as the aforementioned commit's goal of reading the _entire_ firmware.

**Comment by AntonioND** [comment]
Good to hear that there is nothing to do, then.
