### ISSUE TITLE
"make install" builds unnecessary/unused GBA/DS9e variants of maxmod

### ISSUE THREAD

**Issue by asiekierka** [blocksds/sdk#63]

**Comment by AntonioND** [comment]
The devkitPro repository seems to have removed the DS9e version: https://github.com/devkitPro/maxmod/commit/3a7c9f3a666dd6845306aeda826ec2e4fe583f6e

**Comment by asiekierka** [comment]
My proposed solution, if a little quirky, is to replace `install: all` with merely `install:` in the maxmod-side script, and replace `make install` with `make ds install` in the BlocksDS-side script.

**Comment by AntonioND** [comment]
I've removed the DS9E version: https://github.com/blocksds/maxmod/commit/70e352583e426ff48fdd1c142f8a2bdd7af1f3de

It isn't needed to run ``make ds install``, I've just made ``install`` depend on ``ds`` (because this install target only works for BlocksDS anyway):
https://github.com/blocksds/maxmod/commit/45ff69fa346cd24656de1c7a8d85ff31b4a50892
