### ISSUE TITLE
Add ``.`` and ``..`` to ``readdir()``

### ISSUE THREAD

**Issue by AntonioND** [blocksds/sdk#69]
Usually, ``.`` and ``..`` are returned while iterating in a directory that isn't the root of the filesystem. However, FatFs doesn't return them. See https://github.com/DS-Homebrew/GameYob/pull/5 for an example of application affected by this behaviour.

This isn't a critical thing to support, but it may break other applications.

**Comment by LunarLambda** [comment]
Out of curiousity, I checked what Linux does: It's readdir logic does not care whether entries for `dot` and `dot-dot` are returned or not, so it's up to the filesystem driver, which may choose to return them for filesystems that don't "physically" have them (although I couldn't immediately find an example of a driver that definitely does this, since most common Linux filesystems *do* have those physical entries)

This is separate from "path resolution". A filesystem need not have a `..` entry for `x/../y` to work. Though that is it's own weirdness, since there is a difference between canonicalization that touches the filesystem (and resolves links), and resolution that doesn't (i.e. just removes the last component whenever `..` is encountered)

Emulating these entries for NitroFS sounds reasonable, though I'm not sure how often people use relative paths like this in NitroFS to begin with, since it's usually used as read-only file storage and doesn't have symlinks, so proper "navigation" usually isn't needed (and could be replaced with the non-filesystem path resolution I mentioned)

**Comment by LunarLambda** [comment]
I did a bit more digging ~~because I still couldn't find easily accessible filesystems without those entries present~~ and instead decided to check what programs do, generally:

GNU ls, which only lists files but does not traverse them, does not care whether readdir returns `.` and `..`.
Midnight Commander, a TUI file browser, does explicitly stat `..` separately from calling `readdir` for navigational purposes. [source](https://github.com/MidnightCommander/mc/blob/master/src/filemanager/dir.c#L649)

It was already my opinion that programs that want `..` for navigation should explicitly check for it, and that seems to be matched by existing software.

(Did you know that the ISO9660 ("CD") filesystem represents `.` with the empty string and `..` with a single 1-byte?)

Oh, apparently exFAT (and NTFS?) do not have any physical dot/dotdot entries. On Linux, the drivers call a piece of generic Linux filesystem code for emitting them. Windows does something similar. So while standards say it's optional, the expectation seems to still be 'they're always "there"/returned by readdir'

**Comment by asiekierka** [comment]
Thank you for your exhaustive research.

**Comment by AntonioND** [comment]
Thank you both! I'm closing this issue as https://github.com/blocksds/libnds/pull/75 has been merged.
