### ISSUE TITLE
Expose stdout/stderr write pointers

### ISSUE THREAD

**Issue by DieGo367** [blocksds/sdk#73]
The use case for this is creating a custom console implementation. This is possible within a devkitPro project, as one can include `<sys/iosupport.h>` and modify the `devoptab_list` to point to their own write handler. For a BlocksDS project one would need to instead set the `libnds_stdout_write` and `libnds_stderr_write` function pointers. As these have been made internal, it's not possible to create a custom console implementation in BlocksDS without modifying libnds.

**Comment by AntonioND** [comment]
This should be enough: https://github.com/blocksds/libnds/commit/92c406f8d4b14b975018a01b119f0b44b109bcfc

I don't plan on implementing a devoptab-like system because it prevents the linker from removing unused functions. This isn't a big deal with the console (you just waste a few pointers, which isn't nice, but hey), but it really is a problem with filesystem functions. Even if you never use ``mkdir()``, for example, it is referenced by the same structure that refers what you need for ``fopen()``, so both functions are included. With the current implementation only the required code is included in the binary.

**Comment by DieGo367** [comment]
Sweet! Yeah I wasn't sure what would be the ideal way to solve this from the libnds side (otherwise I might've tried to PR it myself), but this is perfect for my use case, thanks.
