### ISSUE TITLE
Docker issue with UTF-16 Title

### ISSUE THREAD

**Issue by Lorenzooone** [blocksds/sdk#86]
When using skylyrac/blocksds:slim-latest to build https://github.com/Lorenzooone/Pokemon-Gen3-to-Gen-X, the title in Makefile.arm9 is wrongly converted from "Pokémon Gen 3 to Gen X" to "Pok??mon Gen 3 to Gen X", with a warning from NDS tool:
WARNING: UTF-16 conversion failed, using fallback.

I am currently updating the repository with the ability to build using Docker. In a few hours, you will be able to check out the Dockerfile that I use in the setup, as to run this test yourselves.
EDIT: The upload is completed.

Direct link to the Dockerfile: https://github.com/Lorenzooone/Pokemon-Gen3-to-Gen-X/blob/main/docker-scripts/build-dockers/Dockerfile

**Comment by AntonioND** [comment]
Well, I've added this:
```
fprintf(stderr, "errno = %d\n", errno);
perror("UTF-16");
```
to the line before [this comment](https://github.com/blocksds/ndstool/blob/96d0f3ee7d183804ae5d4a3f89d3d0a1699c5ad3/source/banner.cpp#L93) and I get this:
```
errno = 84
UTF-16: Invalid or incomplete multibyte or wide character
```

So it really looks like it's a system issue. Maybe because the locale isn't set. I tried adding this, and it seems to fix the warning:
```
export LC_CTYPE=C.UTF-8
```
I haven't even had to do something more drastic like this:
```
export LC_ALL=C.UTF-8
```

Can you give it a try, @Lorenzooone? I can now use the ``é`` character in my banner and melonDS shows it correctly in the ROM information window.

**Comment by Lorenzooone** [comment]
Yeah, works!

**Comment by AntonioND** [comment]
Ok, I've pushed a patch to add it to the dockerfile, and I've updated the "latest" docker images.

https://github.com/blocksds/sdk/commit/bbb1f7a9734e78a3151ffca15d557001a0034b5f
