### ISSUE TITLE
Reduce the amount of RAM used up by the DLDI stub

### ISSUE THREAD

**Issue by asiekierka** [blocksds/sdk#89]
The DLDI stub is currently hardcoded to 16KB. While a few (one?) DLDI drivers are 16KB, most are 8KB and some could feasibly fit in 2-4KB; in addition, a DSi would not need a DLDI driver at all. Ideally, one would free up ~7-8KB of main RAM for most users by resolving this, while not breaking support for 16KB DLDI stubs.

It would be good to evaluate for a way to re-use the DLDI stub area, somehow:

* One idea is to put it at the end of the link script, right before the heap, then adjust the heap size based on the size of the applied DLDI patch.
* Another idea is to repurpose the DLDI stub area as a filesystem cache, currently dynamically allocated as a ~20KB block. This would require more testing on what filesystem cache values bring the most benefit, however.
* More ideas are sought. Feedback welcome!

@lifehackerhansol - requesting a comment if you find some time: based on your understanding on DLDI drivers in practice, do you think this is feasible, or do too many drivers misrepresent their size? (say, claim to use 8KB, but need a 16KB stub space for BSS).

(Even then, it would still be feasible to support re-using the DLDI stub area on DSi, probably...)

**Comment by lifehackerhansol** [comment]
This depends on whether we want to sacrifice older, not as optimized drivers.

So far I've seen two types of drivers:
- They fit within 8KB
    - Most modern carts, as in cartridges you can find easily on eBay or something
- They don't even fit in the devkitPro-standard 16KB (despite saying that it is 16KB in the header...)
    - Acekard RPG NAND, CycloDS/CycloDSi, Neoflash MK5 are ones I've found so far. Though CycloDSi magically works somehow...
    - Acekard RPG NAND is open source though, so if someone wants to take a crack at that 8KB static byte array...

So there is certainly a tradeoff to make for proprietary/legacy drivers. Granted, only about 3 or so, and as you say, can be fixed with some reverse engineering/testing. Unfortunately I can't make any guarantees these will ever be fixed as I don't have them and don't want to make low level changes on things that I can't test.

We (DS-Homebrew) did, however, decide that 8KB is worth it for some of our space-constrained apps, and so far nobody has complained (perhaps out of luck). It's highly unlikely anyone will appear with these carts though.


In terms of the DSi, perhaps we could have a build flag to straight up exclude the driver from the build? (Assuming the application in question is DSi specific.) Not sure how that'd work out though.
